// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6Aw9feOBslpZTrAI1jJLD-NRERpewaRQ',
    appId: '1:857804711691:web:7262123de303d313faa40e',
    messagingSenderId: '857804711691',
    projectId: 'marble-a2d1a',
    authDomain: 'marble-a2d1a.firebaseapp.com',
    storageBucket: 'marble-a2d1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5oAPAB9UQ0hOH00KQeZ9dbvWD1pJ3WPw',
    appId: '1:857804711691:android:4b1afe4968761336faa40e',
    messagingSenderId: '857804711691',
    projectId: 'marble-a2d1a',
    storageBucket: 'marble-a2d1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjJc2Wse7tYmCWF2KUtKQbCJh5hjJ3lzc',
    appId: '1:857804711691:ios:eda633dae00c5b7cfaa40e',
    messagingSenderId: '857804711691',
    projectId: 'marble-a2d1a',
    storageBucket: 'marble-a2d1a.appspot.com',
    iosBundleId: 'com.example.newRothem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjJc2Wse7tYmCWF2KUtKQbCJh5hjJ3lzc',
    appId: '1:857804711691:ios:4dd0767914fa8983faa40e',
    messagingSenderId: '857804711691',
    projectId: 'marble-a2d1a',
    storageBucket: 'marble-a2d1a.appspot.com',
    iosBundleId: 'com.example.newRothem.RunnerTests',
  );
}
